server:
  port: 8003
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.126.222/Bornsport?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  mvc:
    date-format: yyyy-MM-dd    #用于页面获取日期到控制层的日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #用于控制层的日期发送达到页面的日期格式
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8002/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pojo
